### ISSUE TITLE
Request: time since last update

### ISSUE THREAD

**Issue by folrewef** [DSorlov/hasl-platform#14]
It would be great to be able to display the number of minutes since last update. Then there is a very simple mathematical operation that can be made in the head to estimate actual number of minutes to departure.
Time to departure at last update = 5
Time since last update = 2
Actual time to departure (estimated) = 3

**Comment by nesalkiN** [comment]
With the latest update, we have calculation every minute independent of last update time. :)

Add adjust_times: true and (if wanted) hide_departured: true to the card. The card will adjust the time every minute. Very close to a real departure board.

**Comment by folrewef** [comment]
That's perfect!!!

**Comment by folrewef** [comment]
I am trying but no luck. The time is not adjusted. This is how my card is configured:

```
- departures: true
  deviations: true
  timeleft: true
  adjust_time: true
  hide_departed: true
  updated: true
  entities:
    - sensor.storamossen_3
  name: Avgångar från Stora Mossen
  type: 'custom:sl-card'

```

In addition I have set scan_interval to 5 but it only updates every 10 minutes.
