### ISSUE TITLE
timewindow not working

### ISSUE THREAD

**Issue by hekm77** [DSorlov/hasl-platform#23]
The timewindow option not working. Always shows 60 min.
```
sensor:
  - platform: hasl
    ri4key: !secret ri4key
    si2key: !secret si2key
    tl2key: !secret tl2key
    sensors:
      - friendly_name: HASL
        sensor_type: comb
        siteid: !secret siteid
        lines: 471
        direction: 2
        timewindow: 5
      - friendly_name: Trafikstatus
        sensor_type: tl2
```
```
- type: custom:hasl-comb-card
  header: false
  departures: true
  deviations: true
  timeleft: true
  adjust_times: true
  updated: true
  hide_departed: true
  language: sv-SE
  entities:
    - sensor.hasl
```
<img width="502" alt="111" src="https://user-images.githubusercontent.com/22895433/57078309-4eb4d180-6cee-11e9-9456-36f9d4c25343.png">
