### ISSUE TITLE
Displays wrong bus/train lines

### ISSUE THREAD

**Issue by TheRealLouCipher** [DSorlov/hasl-platform#27]
I have a sensor which should show train 43(commuter train), but also shows bus 4 even if i specify traffic_class: train.

sensors.yaml
```
- platform: hasl
  ri4key: !secret sl_ri4key
  si2key: !secret sl_si2key
  tl2key: !secret sl_tl2key
  sensors:
    - friendly_name: Odenplan
      sensor_type: comb
      siteid: 9117
      traffic_class: train
      lines: 43
      direction: 2
      timewindow: 30

```
hasl-comb-card
<img width="500" alt="Skärmavbild 2019-05-10 kl  09 35 40" src="https://user-images.githubusercontent.com/41365311/57512341-a87b5400-730b-11e9-9ca8-453072725460.png">

HA: 0.92.2
custom_component.hasl.sensor: 2.0.1
hasl-comb-card: 2.0.1
