### ISSUE TITLE
Platform not found: sensor.hasl

### ISSUE THREAD

**Issue by Maximus97** [DSorlov/hasl-platform#35]
Hi

I am trying to install this component but get the following error 
`Platform not found: sensor.hasl`

HA version: 0.94.3
Latest version of hasl on master branch

My configuration.yaml is the following
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: hasl
    ri4key: f554d508bcdd4cb582f2b5e4f49ba06e
    si2key: d9732a7ef3074ca4b2163b8f0ffcdc5e
    sensors:
     - friendly_name: Gillestigen
       sensor_type: departures
       siteid: 7524
       lines: 754
       direction: 1
       sensor: binary_sensor.test
     - friendly_name: Trafikstatus
       sensor_type: status

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml<
```
I don't know if additional info is needed?
