### ISSUE TITLE
Platform not found: sensor.hasl

### ISSUE THREAD

**Issue by Cosystick** [DSorlov/hasl-platform#41]
**2019-08-05 17:48:43** WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hasl which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
**2019-08-05 17:48:43** ERROR (MainThread) [homeassistant.components.hassio] Platform not found: sensor.hasl

I am on Hassio 0.96.5

Config looks like this:
```
sensor:  
  - platform: mqtt
    name: "Palmen"
    state_topic: "/home/sensor/palmen"
    value_template: '{{value_json.humidity}}'
    unit_of_measurement: '%'
    device_class: humidity
  - platform: mqtt
    name: "Busken"
    state_topic: "/home/sensor/busken"
    value_template: '{{value_json.humidity}}'
    unit_of_measurement: '%'
    device_class: humidity
  - platform: hasl
    ri4key: !secret sl_realtid_apikey
    si2key: !secret sl_storning_apikey
    tl2key: !secret sl_trafik_apikey
    sensors:
    - friendly_name: Mörby
      sensor_type: departures
      siteid: 9200
      lines: ['14']
      direction: 1
    - friendly_name: Slussen
      sensor_type: departures
      siteid: 9192
      lines: ['14']
      direction: 2
    - friendly_name: Trafikstatus
      sensor_type: status
```
