### ISSUE TITLE
Departures are always empty

### ISSUE THREAD

**Issue by marcus13371337** [DSorlov/hasl-platform#50]
Hi,

Great component, mucho cred!

However, it seems that the API-response might have been changed. Because I don't get any departures into my sensor. This is how it looks:
```
unit_of_measurement: min
refresh_enabled: 'on'
attribution: Stockholms Lokaltrafik
departures: []
deviations: []
last_refresh: '2019-12-01 00:29:24'
next_departure_minutes: '-'
next_departure_time: '-'
deviation_count: 0
friendly_name: Alvik
icon: 'mdi:bus'
```
Looking in https://github.com/DSorlov/hasl-platform/blob/hasl/custom_components/hasl/sensor.py line 392:
```
                    apidata = apidata['ResponseData']['TrafficTypes']
```
When looking in the response from the endpoint I have:
```
{
"StatusCode": 0,
"Message": null,
"ExecutionTime": 79,
"ResponseData": {
"LatestUpdate": "2019-12-01T00:27:06",
"DataAge": 24,
"Metros": [
{
"GroupOfLine": "tunnelbanans gröna linje",
"DisplayTime": "00:31",
"TransportMode": "METRO",
"LineNumber": "18",
"Destination": "Farsta strand",
"JourneyDirection": 2,
"StopAreaName": "Alvik",
"StopAreaNumber": 1201,
"StopPointNumber": 1202,
"StopPointDesignation": "4",
"TimeTabledDateTime": "2019-12-01T00:31:00",
"ExpectedDateTime": "2019-12-01T00:31:00",
"JourneyNumber": 10200,
"Deviations": null
...
```

Has SL updated their response schema?

**Comment by marcus13371337** [comment]
Never mind, looked in the wrong API. However, the problem still exists

**Comment by DSorlov** [comment]
How do your config look? At this time of day there might not be any departures in the next hour or so? All looks good here when trying a known-good config.

**Comment by marcus13371337** [comment]
Looks like this:
```
  - platform: hasl
    ri4key: XX
    si2key: XX
    tl2key: XX
    sensors:
       - friendly_name: Alvik
         sensor_type: departures
         siteid: 9112
         direction: 0
         scan_interval: 60
       - friendly_name: Trafikstatus
         sensor_type: status
         scan_interval: 60
```
